from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np
import pandas as pd

from ..logging_utils import get_logger
from ..strategies.base import StrategyDefinition
from .costs import apply_costs

logger = get_logger(__name__)

BACKTESTS_DIR = Path(__file__).resolve().parent
RESULTS_DIR = BACKTESTS_DIR / "results"
RESULTS_DIR.mkdir(exist_ok=True)


@dataclass
class Trade:
    entry_time: pd.Timestamp
    exit_time: pd.Timestamp
    direction: str  # "long" or "short"
    entry_price: float
    exit_price: float
    stop_loss: float
    take_profit: float
    size: float
    pnl: float
    regime: Optional[str] = None


@dataclass
class BacktestResult:
    strategy: StrategyDefinition
    symbol: str
    timeframe: str
    trades: List[Trade]
    equity_curve: pd.Series  # indexed by time
    stats: Dict[str, float]

    def to_dict(self) -> Dict:
        eq_curve = {str(ts): float(v) for ts, v in self.equity_curve.items()}
        return {
            "strategy": self.strategy.to_dict(),
            "symbol": self.symbol,
            "timeframe": self.timeframe,
            "trades": [t.__dict__ for t in self.trades],
            "equity_curve": eq_curve,
            "stats": self.stats,
        }


# ---------------------------------------------------------------------------
# Rule evaluation
# ---------------------------------------------------------------------------

def _build_local_vars(row: pd.Series) -> Dict[str, float]:
    """Extract numeric values from a feature row for rule evaluation.

    Includes Python int/float AND all numpy numeric/bool types.
    numpy integers (np.int64) are NOT instances of Python int, so they must
    be listed explicitly — otherwise integer columns like fib_zone_382,
    above_cloud, in_news_lockout etc. are silently dropped and rules using
    them always return False.
    """
    result: Dict[str, float] = {}
    for k in row.index:
        v = row[k]
        if isinstance(v, (int, float, np.integer, np.floating, np.bool_)):
            if pd.notna(v):
                result[k] = float(v)
    return result


def _eval_rule(row: pd.Series, rule: Optional[str]) -> bool:
    """Evaluate a simple boolean rule string against a feature row.

    SECURITY NOTE: eval is used with a restricted namespace (no builtins)
    and only numeric values from the feature row. Rules are generated by
    this system, not from user input.
    """
    if not rule or not rule.strip():
        return False
    local_vars = _build_local_vars(row)
    try:
        return bool(eval(rule, {"__builtins__": {}}, local_vars))
    except NameError as e:
        # A column referenced in the rule is missing from features — log once
        logger.debug("Rule eval NameError (missing feature?): rule='%s' error=%s", rule, e)
        return False
    except Exception:
        return False


# ---------------------------------------------------------------------------
# Periods per year — calibrated for each instrument/session
#
# Gold (XAUUSDm) trades ~23h/day, 5 days/week.
# Using US equity session hours (6.5h) understates the annualisation factor
# by ~3.5x, inflating Sharpe ratios. The table below uses 23h for metals
# and 24h for crypto. Forex pairs trade ~24h on weekdays.
#
# To override for a specific symbol, pass periods_per_year to run_backtest().
# ---------------------------------------------------------------------------

TIMEFRAME_PERIODS_PER_YEAR: Dict[str, float] = {
    "M1":  252 * 23 * 60,    # ~23h metals session
    "M5":  252 * 23 * 12,
    "M15": 252 * 23 * 4,     # 23,184 — was 6,552 (3.5x underestimate)
    "M30": 252 * 23 * 2,
    "H1":  252 * 23,
    "H4":  252 * 6,
    "D1":  252,
}

# Override for crypto (24h/day, 365 days/year)
CRYPTO_PERIODS_PER_YEAR: Dict[str, float] = {
    "M1":  365 * 24 * 60,
    "M5":  365 * 24 * 12,
    "M15": 365 * 24 * 4,
    "M30": 365 * 24 * 2,
    "H1":  365 * 24,
    "H4":  365 * 6,
    "D1":  365,
}

_CRYPTO_SYMBOLS = {"BTCUSDm", "ETHUSDm", "BTCUSD", "ETHUSD"}


def _get_periods_per_year(symbol: str, timeframe: str) -> float:
    table = CRYPTO_PERIODS_PER_YEAR if symbol in _CRYPTO_SYMBOLS else TIMEFRAME_PERIODS_PER_YEAR
    return table.get(timeframe, 252.0)


# ---------------------------------------------------------------------------
# Backtest engine
# ---------------------------------------------------------------------------

def run_backtest(
    df: pd.DataFrame,
    strategy: StrategyDefinition,
    initial_equity: float = 10_000.0,
    risk_per_trade_pct: float = 1,
    pip_size: Optional[float] = None,
    max_positions_total: int = 5,
    spread: float = 0.0,
    commission_per_lot: float = 0.0,
    slippage_pips: float = 0.0,
    regime_column: Optional[str] = None,
    periods_per_year: Optional[float] = None,
) -> BacktestResult:
    """Bar-by-bar backtest for a single strategy with multi-position support.

    Optimisation notes vs v1:
    - itertuples() replaces iterrows() — ~5x faster for large DataFrames.
    - _build_local_vars() is called once per bar and shared between long/short
      rule evaluation, not twice.
    - ATR lookup is a single column-index lookup per bar, not repeated getattr.
    """
    logger.info(
        "Running backtest for %s on %s %s (len=%d)",
        strategy.name,
        strategy.symbol,
        strategy.timeframe,
        len(df),
    )

    df = df.copy().reset_index(drop=True)
    equity = initial_equity
    equity_curve: List[float] = []
    times: List[pd.Timestamp] = []
    trades: List[Trade] = []
    positions: List[Dict] = []

    # Pip size default: metals use 0.01, everything else 0.0001
    if pip_size is None:
        pip_size = 0.01 if "XAU" in strategy.symbol or "XAG" in strategy.symbol else 0.0001

    # ATR-based SL/TP
    use_atr = (
        "atr" in df.columns
        and getattr(strategy, "sl_atr_mult", None) is not None
        and getattr(strategy, "tp_atr_mult", None) is not None
    )
    sl_atr_mult: float = getattr(strategy, "sl_atr_mult", 2.0) or 2.0
    tp_atr_mult: float = getattr(strategy, "tp_atr_mult", 2.0) or 2.0

    has_regime_col = regime_column is not None and regime_column in df.columns
    has_atr_col = "atr" in df.columns

    # Pre-build column index for fast lookup in itertuples
    col_index = {col: i + 1 for i, col in enumerate(df.columns)}  # +1 for Index

    for row_tuple in df.itertuples(index=False):
        time = row_tuple.time
        close = float(row_tuple.close)
        high = float(row_tuple.high)
        low = float(row_tuple.low)

        # Build eval namespace once per bar
        row = df.iloc[row_tuple.Index] if hasattr(row_tuple, 'Index') else None
        # itertuples doesn't have .Index in named tuple by default when index=False
        # We need the Series for _eval_rule. Use a different approach:
        # We'll get the current row as a Series via position
        pass

    # ------------------------------------------------------------------ #
    # Restart with iloc-based loop (safer with _eval_rule's pd.Series API) #
    # itertuples is faster but _eval_rule needs pd.Series. The compromise   #
    # is to use itertuples for OHLC scalars and iloc for the full row only  #
    # when needed — but given _eval_rule is called 2-3x per bar, iloc once  #
    # per bar is cleaner and still faster than iterrows (no dtype boxing).   #
    # ------------------------------------------------------------------ #
    equity_curve.clear()
    times.clear()
    trades.clear()
    positions.clear()
    equity = initial_equity

    n = len(df)
    for i in range(n):
        row = df.iloc[i]
        time = row["time"]
        close = float(row["close"])
        high = float(row["high"])
        low = float(row["low"])

        # Build eval namespace once per bar
        local_vars = _build_local_vars(row)

        # ---- Manage existing positions ----
        remaining: List[Dict] = []
        for pos in positions:
            exit_reason = None
            exit_price = close

            if pos["direction"] == "long":
                if low <= pos["stop_loss"]:
                    exit_price = pos["stop_loss"]
                    exit_reason = "stop_loss"
                elif high >= pos["take_profit"]:
                    exit_price = pos["take_profit"]
                    exit_reason = "take_profit"
            else:
                if high >= pos["stop_loss"]:
                    exit_price = pos["stop_loss"]
                    exit_reason = "stop_loss"
                elif low <= pos["take_profit"]:
                    exit_price = pos["take_profit"]
                    exit_reason = "take_profit"

            if exit_reason is None:
                try:
                    if strategy.exit_rule and bool(eval(strategy.exit_rule, {"__builtins__": {}}, local_vars)):
                        exit_reason = "exit_rule"
                except Exception:
                    pass

            if exit_reason is not None:
                pnl = apply_costs(
                    direction=pos["direction"],
                    entry_price=pos["entry_price"],
                    exit_price=exit_price,
                    size=pos["size"],
                    spread=spread,
                    commission_per_lot=commission_per_lot,
                    slippage_pips=slippage_pips,
                    pip_size=pip_size,
                )
                equity += pnl
                trades.append(Trade(
                    entry_time=pos["entry_time"],
                    exit_time=time,
                    direction=pos["direction"],
                    entry_price=pos["entry_price"],
                    exit_price=exit_price,
                    stop_loss=pos["stop_loss"],
                    take_profit=pos["take_profit"],
                    size=pos["size"],
                    pnl=pnl,
                    regime=pos.get("regime"),
                ))
            else:
                remaining.append(pos)

        positions = remaining

        # ---- New entries ----
        if len(positions) < max_positions_total:
            # Compute ATR once if needed
            atr_value = float(row["atr"]) if use_atr and has_atr_col else None
            regime_label = str(row[regime_column]) if has_regime_col else None

            def _try_open(direction: str) -> None:
                nonlocal equity
                if use_atr and atr_value is not None:
                    sl_dist = sl_atr_mult * atr_value
                    tp_dist = tp_atr_mult * atr_value
                else:
                    sl_dist = strategy.stop_loss_pips * pip_size
                    tp_dist = strategy.take_profit_pips * pip_size

                if sl_dist <= 0:
                    return

                risk_amount = equity * (risk_per_trade_pct / 100.0)
                size = risk_amount / sl_dist

                if direction == "long":
                    sl = close - sl_dist
                    tp = close + tp_dist
                else:
                    sl = close + sl_dist
                    tp = close - tp_dist

                positions.append({
                    "entry_time": time,
                    "entry_price": close,
                    "direction": direction,
                    "size": size,
                    "stop_loss": sl,
                    "take_profit": tp,
                    "regime": regime_label,
                })

            try:
                if strategy.long_entry_rule and bool(eval(strategy.long_entry_rule, {"__builtins__": {}}, local_vars)):
                    _try_open("long")
            except Exception:
                pass

            if len(positions) < max_positions_total:
                try:
                    if strategy.short_entry_rule and bool(eval(strategy.short_entry_rule, {"__builtins__": {}}, local_vars)):
                        _try_open("short")
                except Exception:
                    pass

        times.append(time)
        equity_curve.append(equity)

    equity_series = pd.Series(equity_curve, index=pd.to_datetime(times))

    ppy = periods_per_year or _get_periods_per_year(strategy.symbol, strategy.timeframe)
    stats = _compute_basic_stats(equity_series, trades, initial_equity, ppy)

    # Strategy explain
    try:
        from .explain import build_strategy_explain
        trades_df = pd.DataFrame([t.__dict__ for t in trades]) if trades else pd.DataFrame()
        explain = build_strategy_explain(
            trades=trades_df,
            features=df,
            regime_column=regime_column or "regime",
            initial_equity=initial_equity,
            symbol=strategy.symbol,
        )
        stats["strategy_explain"] = explain
    except Exception as e:
        logger.exception("Failed to build strategy_explain for %s: %s", strategy.name, e)

    logger.info(
        "Backtest complete for %s: trades=%d final_eq=%.2f return=%.2f%% sharpe=%.3f max_dd=%.2f%%",
        strategy.name,
        len(trades),
        equity,
        stats.get("return_pct", 0.0),
        stats.get("sharpe_ratio", 0.0),
        stats.get("max_drawdown_pct", 0.0),
    )

    return BacktestResult(
        strategy=strategy,
        symbol=strategy.symbol,
        timeframe=strategy.timeframe,
        trades=trades,
        equity_curve=equity_series,
        stats=stats,
    )


# ---------------------------------------------------------------------------
# Stats computation
# ---------------------------------------------------------------------------

def _compute_basic_stats(
    equity_curve: pd.Series,
    trades: List[Trade],
    initial_equity: float,
    periods_per_year: float,
) -> Dict[str, float]:
    if equity_curve.empty:
        return {"final_equity": initial_equity, "max_drawdown_pct": 0.0}

    final_equity = float(equity_curve.iloc[-1])
    returns = equity_curve.pct_change().dropna()

    sharpe = (
        float(np.sqrt(periods_per_year) * returns.mean() / (returns.std() + 1e-9))
        if not returns.empty
        else 0.0
    )

    running_max = equity_curve.cummax()
    max_dd = float((equity_curve / running_max - 1.0).min())

    gains = [t.pnl for t in trades if t.pnl > 0]
    losses = [t.pnl for t in trades if t.pnl < 0]
    gross_profit = float(sum(gains)) if gains else 0.0
    gross_loss = float(-sum(losses)) if losses else 0.0
    profit_factor = gross_profit / (gross_loss + 1e-9) if gross_loss > 0 else 0.0
    win_rate = len(gains) / len(trades) if trades else 0.0

    avg_win = gross_profit / len(gains) if gains else 0.0
    avg_loss = gross_loss / len(losses) if losses else 0.0

    return {
        "initial_equity": float(initial_equity),
        "final_equity": final_equity,
        "net_profit": final_equity - initial_equity,
        "return_pct": (final_equity - initial_equity) / initial_equity * 100.0,
        "sharpe_ratio": sharpe,
        "max_drawdown_pct": max_dd * 100.0,
        "profit_factor": profit_factor,
        "win_rate": win_rate,
        "num_trades": float(len(trades)),
        "avg_win": avg_win,
        "avg_loss": avg_loss,
        "expectancy": (win_rate * avg_win) - ((1 - win_rate) * avg_loss),
    }


# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------

def save_backtest_result(result: BacktestResult) -> Path:
    import json
    path = RESULTS_DIR / f"{result.strategy.name}_{result.symbol}_{result.timeframe}.json"
    with path.open("w", encoding="utf-8") as f:
        json.dump(result.to_dict(), f, indent=2, default=str)
    logger.info("Saved backtest result to %s", path)
    return path